### PR TITLE
Distinguish between the original method and a method missing proc.

### LINKED ISSUE #951: Weird interaction between stubs on super- and subclasses
If I set expectations or stubs on classes, something weird happens, according to the descriptions below (which might explain things better and more concisely than I could otherwise, so here):

```ruby
require 'rspec/core'

class Model
  def real_method
  end
end
class SubModel < Model; end

describe "stubs on sub- and superclasses" do
  describe "setting both stubs on the superclass" do
    it "works fine" do
      allow(Model).to receive(:non_existing_method)
      allow(Model).to receive(:non_existing_method)
    end
  end

  describe "setting both stubs on the subclass" do
    it "works fine" do
      allow(SubModel).to receive(:non_existing_method)
      allow(SubModel).to receive(:non_existing_method)
    end
  end

  describe "setting stubs on both super- and subclass" do
    context "when the two stubs are for different methods" do
      it "works fine" do
        allow(Model).to receive(:non_existing_method)
        allow(SubModel).to receive(:other_non_existing_method)
      end
    end

    context "when the method already exists in a higher-up superclass" do
      let(:inherited_method) { :to_s }

      it "works fine" do
        allow(Model).to receive(inherited_method)
        allow(SubModel).to receive(inherited_method)
      end
    end

    context "when the method is implemented in the base class of the two relevant classes" do
      let(:real_method) { :real_method }

      it "breaks" do
        allow(Model).to receive(real_method)
        allow(SubModel).to receive(real_method)
      end
    end

    context "when the method is not implemented at all" do
      let(:non_existing_method) { :non_existing_method }

      it "breaks" do
        allow(Model).to receive(non_existing_method)
        allow(SubModel).to receive(non_existing_method)
      end
    end

    context "when the existing implementation was another stub" do
      let(:stubbed_method) { :non_existing_method }

      before :each do
        allow(Model).to receive(stubbed_method)
      end

      it "breaks" do
        allow(Model).to receive(stubbed_method)
        allow(SubModel).to receive(stubbed_method)
      end
    end
  end
end
```

```
$ rspec bug_spec.rb
....FFF

Failures:

  1) stubs on sub- and superclasses setting stubs on both super- and subclass when the method is implemented in the base class of the two relevant classes breaks
     Failure/Error: allow(SubModel).to receive(real_method)
     NoMethodError:
       undefined method `unbind' for #<Proc:0x0000000297b718>
     # ./bug_spec.rb:46:in `block (4 levels) in <top (required)>'

  2) stubs on sub- and superclasses setting stubs on both super- and subclass when the method is not implemented at all breaks
     Failure/Error: allow(SubModel).to receive(non_existing_method)
     NoMethodError:
       undefined method `unbind' for #<Proc:0x00000002978658>
     # ./bug_spec.rb:55:in `block (4 levels) in <top (required)>'

  3) stubs on sub- and superclasses setting stubs on both super- and subclass when the existing implementation was another stub breaks
     Failure/Error: allow(SubModel).to receive(stubbed_method)
     NoMethodError:
       undefined method `unbind' for #<Proc:0x00000002975368>
     # ./bug_spec.rb:68:in `block (4 levels) in <top (required)>'

Finished in 0.00582 seconds (files took 0.08164 seconds to load)
7 examples, 3 failures

Failed examples:

rspec ./bug_spec.rb:44 # stubs on sub- and superclasses setting stubs on both super- and subclass when the method is implemented in the base class of the two relevant classes breaks
rspec ./bug_spec.rb:53 # stubs on sub- and superclasses setting stubs on both super- and subclass when the method is not implemented at all breaks
rspec ./bug_spec.rb:66 # stubs on sub- and superclasses setting stubs on both super- and subclass when the existing implementation was another stub breaks
```

Let me know if you need more information or if I'm just doing something wrong. The code I discovered this issue in worked fine with RSpec 2.99 without any warnings.

### PR DESCRIPTION
**Pull request by myronmarston**
Before, we would return a proc that invokes `method_missing`
from `original_method`, but it wasn’t a `Method` object
and couldn’t be bound, leading to `NoMethodError` in an
edge case.

Fixes #951.

### CODE REVIEW

**Comment by myronmarston** [comment]
Got this green on travis.  Anyone want to review it, @rspec/rspec ?

**Comment by soulcutter** [comment]
Looks good to me :shipit:
