### ISSUE TITLE
Aliased method disapper on rspec-mocks 3.4.1

### ISSUE THREAD

**Issue by shigi** [rspec/rspec-mocks#1057]
```ruby
class A
  def g1
    1
  end
end

class B < A
  def f
    g2
  end

  alias g2 g1
end

describe '#f', order: true do
  let(:b) { B.new }

  it 'call B#g2' do
    expect_any_instance_of(B).to receive(:g2).with(no_args)
    b.f
  end

  it { expect(b.f).to eq 1 }
end
```

This works fine on rspec-mocks 3.4.0.
But on rspec-mocks 3.4.1, below error occurs.

```
Failures:

  1) #f 
     Failure/Error: g2

     NameError:
       undefined local variable or method `g2' for #<B:0x007fd11f2f15c8>
     # ./test_spec.rb:9:in `f'
     # ./test_spec.rb:23:in `block (2 levels) in <top (required)>'
```

The version of Ruby is 2.1.5 and 2.2.3.

**Comment by myronmarston** [comment]
I think #1043 is the source of the problem.  I don't understand how it causes the failure yet, though.

**Comment by jrafanie** [comment]
I'll try to take a look at this @myronmarston since I added #1043.  I agree, that change is probably at fault.

**Comment by jrafanie** [comment]
Ok, I figured out what's happening.

It turns out `Method#owner` is terribly inconsistent to determine which class implements an aliased method.

See [here](https://gist.github.com/jrafanie/0e5b8a9f4e8b4f84913f)

**Comment by jrafanie** [comment]
@myronmarston this "hack" fixes it for ruby 2.1.x, 2.2.x but `Method#original_name` doesn't exist in ruby 2.0 and earlier.

```diff
diff --git a/lib/rspec/mocks/any_instance/recorder.rb b/lib/rspec/mocks/any_instance/recorder.rb
index 8651e02..691f8a4 100644
--- a/lib/rspec/mocks/any_instance/recorder.rb
+++ b/lib/rspec/mocks/any_instance/recorder.rb
@@ -208,7 +208,9 @@ module RSpec
           return unless public_protected_or_private_method_defined?(method_name)

           alias_method_name = build_alias_method_name(method_name)
-          @backed_up_method_owner[method_name.to_sym] ||= @klass.instance_method(method_name).owner
+          method = @klass.instance_method(method_name)
+          owner = method.original_name == method ? @klass.instance_method(method_name).owner : @klass
+          @backed_up_method_owner[method_name.to_sym] ||= owner
           @klass.class_exec do
             alias_method alias_method_name, method_name
           end
diff --git a/spec/rspec/mocks/any_instance_spec.rb b/spec/rspec/mocks/any_instance_spec.rb
index a3b6a7e..1097fe9 100644
--- a/spec/rspec/mocks/any_instance_spec.rb
+++ b/spec/rspec/mocks/any_instance_spec.rb
@@ -5,12 +5,22 @@ module AnyInstanceSpec
     def foo(_a)
       'bar'
     end
+
+    def g1
+      1
+    end
   end

   class ParentClass < GrandparentClass
     def foo
       super(:a)
     end
+
+    def f
+      g2
+    end
+
+    alias g2 g1
   end

   class ChildClass < ParentClass
@@ -40,6 +50,17 @@ module RSpec
         end
       end

+      context  '#f' do
+        let(:parent) { AnyInstanceSpec::ParentClass.new }
+
+        it 'call ParentClass#g2' do
+          expect_any_instance_of(AnyInstanceSpec::ParentClass).to receive(:g2).with(no_args)
+          parent.f
+        end
+
+        it { expect(parent.f).to eq 1 }
+      end
+
       context "invocation order" do
         context "when stubbing" do
           it "raises an error if 'with' follows 'and_return'" do
```

**Comment by jrafanie** [comment]
So, owner for aliased methods isn't consistent per ruby versions... We can check if the method is an alias by comparing the method name vs. `original_name` but then `original_name` was added in 2.1 so we'd have to figure out a different solution for 2.0 and earlier.

**Comment by jrafanie** [comment]
To be honest, I don't know what `owner` should say for an aliased method or a class that subclasses a class with the aliased_method.

**Comment by myronmarston** [comment]
Given that the bug addressed by #1043 only manifested on Ruby 2.3, can we restore the original pre-#1043 behavior for `RUBY_VERSION < '2.3.0'` and then have the fix from #1043 in effect only on Ruby 2.3? On 2.3 you could also use `original_name` to guard against the alias issue, right?

**Comment by jrafanie** [comment]
@myronmarston opened #1060 to fix this. Note, since we only check `owner` for ruby 2.3+ and `owner` for aliased methods appears to do the right thing in ruby 2.3.0, we don't need to check `original_name`.  Namely, we only need to restore the aliased method to the class if that class added the alias, which is what `owner` does for us with ruby 2.3+. See: https://gist.github.com/jrafanie/0e5b8a9f4e8b4f84913f#file-output-txt-L43

**Comment by jrafanie** [comment]
@shigi can you try master now?

I believe something like this in your Gemfile should let you try it out:

`gem 'rspec-mocks', :github => "rspec/rspec-mocks", :branch => "master"`

**Comment by shigi** [comment]
@jrafanie I tried master branch and it worked fine!
Thank you for your fix!

**Comment by jrafanie** [comment]
@shigi Great!  Thank you for reporting the issue and confirming it worked for you.  

The `(allow|expect)_any_instance_of(...)` code is quite complicated so I appreciate your confirmation!
